### PR TITLE
Add a page that refers to the text files

### PR DESCRIPTION
**Pull request by timothymcmackin**
Preview: https://docs-staging-git-links-to-txt-files-trili-tech.vercel.app/reference/textfiles

### CODE REVIEW

**Review by beatalipska — APPROVED** [review]
🚀 love it!

**Comment by NicNomadic** [comment]
Maybe it's also worth to refer to this page in the landing page, section <https://docs.tezos.com/overview/#scope-of-this-site-and-other-tezos-documentation>?
Up to you, LGTM.

**Review by NicNomadic — APPROVED** [review]
LGTM, modulo non-blocking question above.

**Comment by timothymcmackin** [comment]
> Maybe it's also worth to refer to this page in the landing page, section https://docs.tezos.com/overview/#scope-of-this-site-and-other-tezos-documentation? Up to you, LGTM.

Good idea, I added links from two other pages.

**Pull request merged**
