### PR TITLE
Script to concatenate MD files

### PR DESCRIPTION
**Pull request by timothymcmackin**
This script concatenates all MD files and strips the markdown code into a single text file so you can feed it to an LLM. Run it by running `npm run concat`. It outputs to `allPageSourceFiles.txt` and if I've done it correctly, that file will be at https://docs.tezos.com/allPageSourceFiles.txt.

### CODE REVIEW

**Review by beatalipska — APPROVED** [review]
magic!

**Comment by NicNomadic** [comment]
I think it's mostly fine, except that you should skip the glossary, which is included as raw HTML, which is not very useful, because unreadable. Anyways, there's a readable copy of it in the Octez doc.

**Comment by timothymcmackin** [comment]
> I think it's mostly fine, except that you should skip the glossary, which is included as raw HTML, so not very useful because unreadable. Anyways, there's a readable copy of it in the Octez doc.

Not sure if we should include it or not. LLMs may be able to read it as it is. I guess it depends on whether you're using this site alone or together with the Octez docs.

**Comment by NicNomadic** [comment]
> Not sure if we should include it or not. LLMs may be able to read it as it is. I guess it depends on whether you're using this site alone or together with the Octez docs.

I'm pretty sure they don't interpret it the right way, because the HTML structure doesn't even expose it as a glossary, you just have some indented words and paragraphs, not marked as terms and definitions. But it's not a big deal if we leave it in, it's pretty small compared to other pieces of code (JS, HTML) inlined in the tutorials.

**Review by NicNomadic — DISMISSED** [review]
LGTM

**Comment by timothymcmackin** [comment]
Added filters for glossary and tutorials section.

**Comment by timothymcmackin** [comment]
I changed this script to strip the markdown out so it would be plain text -- probably easier for the LLM to read.

**Review by beatalipska — APPROVED** [review]

**Pull request merged**
